Got prompt working

diff --git a/dot_bash_aliases b/dot_bash_aliases
--- a/dot_bash_aliases
+++ b/dot_bash_aliases
@@ -2,12 +2,18 @@
 
 source ~/.aliases
 
-human_hostname=$(echo $HOSTNAME | sed 's/-\?[0-9a-f]\{8\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{12\}//')
-# This doesn't update when you change branches
-#branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
-#export PS1="\e[1;36m\u@$human_hostname\e[m\e[1;32m \w \e[m\e[1;33m$branch${branch+ }\e[m$ "
-export PS1="\e[1;36m\u@$human_hostname\e[m\e[1;32m \w \e[m$ "
+# Reomove UUIDs, optionally prefixed by a dash, from the hostname
+_human_hostname=$(echo $HOSTNAME | sed 's/-\?[0-9a-f]\{8\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{12\}//')
+_git_branch() {
+    branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
+    echo ${branch}${branch:+" "} # "alternate value", used to add a space only if branch is nonempty
+}
+_print_if_nonzero() {
+    if [[ "$1" -ne 0 ]]; then echo "$1 "; fi
+}
+PROMPT_COMMAND='_exit_status=$?' # This runs before $PS1 is evaluated, saving the exit status
+# Single quotes cause this to be reevaluated each prompt, to keep branch up to date
+export PS1='\e[1;36m\u@$_human_hostname\e[m\e[1;32m \w \e[m\e[1;33m$(_git_branch)\e[m\e[1;35m$(_print_if_nonzero $_exit_status)\e[m$ '
 
 # Up arrow history searching
-# This is causing a glitch with text overwriting?
-#bind '"\e[A": history-search-backward'
+bind '"\e[A": history-search-backward'
